# frontend/Dockerfile
FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Falls ein Build-Schritt notwendig ist, zum Beispiel mit webpack:
RUN npm run build

# Verwende Nginx als Webserver
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
